function scrollIn(event){
    //console.log('scroll in',arguments);
    var node = $(this).data('node');
    if(node.scrollIn){
      node.scrollIn();
    }
}

function scrollOut(event){
    //console.log('scroll in',arguments);
    var node = $(this).data('node');
    if(node.scrollOut){
      node.scrollOut();
    }
}


$(document).ready(function(){
  console.log('zoe letters');
  
  var letters = [
  //{"letter":"a","label":"Apple","image":"12197659796_46448fa0d3_o.jpg"},
  {
    multi:[
      {
        "letter":"a",
        "label":"Alligator",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Alligator_Canberra_Zoo.jpg/1280px-Alligator_Canberra_Zoo.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/alligator.mp3",
        "color":"#4caf50"
      },    
      {
        "letter":"a",
        "label":"Alpaca",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Rose_Hill_Farm_Alpaca_03.jpg/768px-Rose_Hill_Farm_Alpaca_03.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/alpaca.mp3",
        "color":"tan"
      },
      {
        "letter":"a",
        "label":"Anteater",
        "image":"https://upload.wikimedia.org/wikipedia/commons/6/68/Myrmecophaga_tridactyla_by_anagoria.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/anteater.mp3",
        "color":"#4caf50"
      },
      {
        "letter":"a",
        "label":"Antelope",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Blesbok_sa_2003.jpg/1280px-Blesbok_sa_2003.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/antelope.mp3",
        "color":"tan"
      }
    ]
  },
  {
    multi:[
      {
        "letter":"b",
        "label":"Bird",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cyanocitta-cristata-004.jpg/1280px-Cyanocitta-cristata-004.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/robin.mp3"
      },    
      {
        "letter":"b",
        "label":"Bat",
        "image":"https://upload.wikimedia.org/wikipedia/commons/d/d2/Pteropus_conspicillatus_with_baby.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/bat.mp3",
        "color":"grey"
      },
      {
        "letter":"b",
        "label":"Bee",
        "image":"https://upload.wikimedia.org/wikipedia/commons/d/d0/Abeille_Bee_%286231908274%29.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/bee.mp3",
        "color":"yellow"
      },
      {
        "letter":"b",
        "label":"Buffalo",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Lone_Buffalo_AWBF-6.jpg/1280px-Lone_Buffalo_AWBF-6.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/buffalo.mp3",
        "color":"brown"
      },
      {
        "letter":"b",
        "label":"Butterfly",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Marbled_fritillary_%28Brenthis_daphne%29.jpg/1280px-Marbled_fritillary_%28Brenthis_daphne%29.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/butterfly.mp3"
      }
    ]
  },
  {
    multi:[
    {
    "letter":"c",
    "label":"Cat",
    "image":"https://upload.wikimedia.org/wikipedia/commons/4/4d/Cat_November_2010-1a.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/cat.mp3"
    },
    {
    "letter":"c",
    "label":"Camel",
    "image":"https://upload.wikimedia.org/wikipedia/commons/6/6d/Brosen_camelus1.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/camel.mp3",
    "color":"tan"
    },
    {
    "letter":"c",
    "label":"Chicken",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Gallus_gallus_domesticus_LC0262.jpg/1024px-Gallus_gallus_domesticus_LC0262.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/chicken.mp3",
    "color":"tomato"
    },
    {
    "letter":"c",
    "label":"Cow",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Light_Roan_Shorthorn_Heifer_DSCN1872b.jpg/1280px-Light_Roan_Shorthorn_Heifer_DSCN1872b.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/cow.mp3"
    },
    {
    "letter":"c",
    "label":"Crow",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Corvus_corax_ad_berlin_090516.jpg/1280px-Corvus_corax_ad_berlin_090516.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/crow.mp3",
    "color":"grey"
    }
    ]
  },
  {
    multi:[
      {
        "letter":"d",
        "label":"Dog",
        "image":"https://upload.wikimedia.org/wikipedia/commons/b/b3/Siberian_husky2.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/dog.mp3"
      },
      {
        "letter":"d",
        "label":"Dove",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ducula_spilorrhoa_2.jpg/1140px-Ducula_spilorrhoa_2.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/dove.mp3",
        "color":"ivory"
      },
      {
        "letter":"d",
        "label":"Duck",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/White-cheeked_Pintail_RWD.jpg/1024px-White-cheeked_Pintail_RWD.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/duck.mp3"
      }
    ]
  },
  {
    multi:[
      {
        "letter":"e",
        "label":"Elephant",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Elephant_%28Loxodonta_Africana%29_05.jpg/1280px-Elephant_%28Loxodonta_Africana%29_05.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/elephant.mp3",
        "color":"silver"
      }
    ]
  },
  {
    multi:[
      {
        "letter":"f",
        "label":"Fox",
        "image":"https://upload.wikimedia.org/wikipedia/commons/d/df/Fox_study_6.jpg",
        "textSound":"Ring-ding-ding-ding-dingeringeding!",
        "color":"orange"
      },
      {
        "letter":"f",
        "label":"Falcon",
        "image":"https://upload.wikimedia.org/wikipedia/commons/0/0c/Red-Necked_Falcon.JPG",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/falcon.mp3"
      },
      {
        "letter":"f",
        "label":"Ferret",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Ferret_2008.png/1024px-Ferret_2008.png",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/ferret.mp3"
      },
      {
        "letter":"f",
        "label":"Frog",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Common_frog_rana_temporaria.jpg/1280px-Common_frog_rana_temporaria.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/frog.mp3",
        "color":"forestgreen"
      }
    ]
  },
  {
    multi:[
      {
        "letter":"g",
        "label":"Giraffe",
        "image":"https://upload.wikimedia.org/wikipedia/commons/0/02/Giraffe_Ithala_KZN_South_Africa_Luca_Galuzzi_2004.JPG",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/giraffe.mp3",
        "color":"yellow"
      },
      {
        "letter":"g",
        "label":"Guinea Pig",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Cavia.jpg/720px-Cavia.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/guinea-pig.mp3"
      }    
    ]
  },
  {
    multi:[
      {
        "letter":"h",
        "label":"Horse",
        "image":"https://upload.wikimedia.org/wikipedia/commons/e/e6/IcelandicHorseInWinter.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/horse.mp3",
        "color":"brown"
      },
      {
        "letter":"h",
        "label":"Hedgehog",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Erinaceus_europaeus_LC0119.jpg/1280px-Erinaceus_europaeus_LC0119.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/hedgehog.mp3"
      },
      {
        "letter":"h",
        "label":"Hippopotamus",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Hroch_obojzivelny.jpg/1280px-Hroch_obojzivelny.jpg",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/hippopotamus.mp3",
        "color":"pink"
      },
      {
        "letter":"h",
        "label":"Hyena",
        "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Hyene_amneville.JPG/1280px-Hyene_amneville.JPG",
        "sound":"https://www.google.com/logos/fnbx/animal_sounds/hyena.mp3"
      }
    ]
  },
  {
    multi:[
    {
      "letter":"i",
      "label":"Iguana",
      "image":"https://upload.wikimedia.org/wikipedia/commons/7/7f/Iguana_V.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/lizard.mp3",
      "color":"lime"
    }
    ]
  },
  {
    "letter":"j",
    "label":"Jellyfish",
    "image":"https://upload.wikimedia.org/wikipedia/commons/4/44/Jelly_cc11.jpg",
    "textSound":"Blub Blub",
    "color":"#2196f3"
  },
  {
    multi:[
    {
    "letter":"k",
    "label":"Koala",
    "image":"https://upload.wikimedia.org/wikipedia/commons/2/25/Friendly_Female_Koala.JPG",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/g-sound.mp3"
    },
    {
    "letter":"k",
    "label":"Komodo Dragon",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Varanus_komodoensis5.jpg/1280px-Varanus_komodoensis5.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/komodo-dragon.mp3"
    }
    ]
  },
  {
    multi:[
    {
    "letter":"l",
    "label":"Lion",
    "image":"https://upload.wikimedia.org/wikipedia/commons/b/b5/Lion_d%27Afrique.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/lion.mp3",
    "color":"gold"
    },
    {
    "letter":"l",
    "label":"Leopard",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Amur_Leopard_%28219987133%29.jpeg/1280px-Amur_Leopard_%28219987133%29.jpeg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/leopard.mp3",
    "color":"gold"
    }

    ]
  },
  {
    multi:[
    {
      "letter":"m",
    "label":"Mouse",
    "image":"https://upload.wikimedia.org/wikipedia/commons/8/83/Mouse-19-Dec-2004.jpg",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/m-sound-mouse.mp3"
    },
    {
    "letter":"m",
    "label":"Moose",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/J%C3%A1vorszarvas.jpg/1280px-J%C3%A1vorszarvas.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/moose.mp3"
    }
    ]
  },
  {
    "letter":"n",
    "label":"Nautilus",
    "image":"https://upload.wikimedia.org/wikipedia/commons/d/d5/Nautilus_Palau.JPG",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/x-sound.mp3",
    "color":"#2196f3"
  },
  {
    multi:[
    {
      "letter":"o",
      "label":"Ostrich",
      "image":"https://upload.wikimedia.org/wikipedia/commons/2/28/Ostrich_male_RWD.jpg"
    },
    {
      "letter":"o",
      "label":"Otter",
      "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Curious_Otter_%2815067291649%29.jpg/1280px-Curious_Otter_%2815067291649%29.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/otter.mp3"
    },
    {
      "letter":"o",
      "label":"Owl",
      "image":"https://upload.wikimedia.org/wikipedia/commons/3/39/Athene_noctua_%28cropped%29.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/owl.mp3"
    }
    ]
  },
  {
    multi:[
    {  
      "letter":"p",
      "label":"Parrot",
      "image":"https://upload.wikimedia.org/wikipedia/commons/d/d7/Amazona_autumnalis_-The_Parrot_Zoo%2C_Friskney%2C_Lincolnshire%2C_England-8a-2c.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/african-grey-parrot.mp3",
      "color":"#4caf50"
    },
    {  
      "letter":"p",
      "label":"Panda",
      "image":"https://upload.wikimedia.org/wikipedia/commons/c/c2/Pandas_Chengdu.JPG",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/panda.mp3"
    },
    {  
      "letter":"p",
      "label":"Penguin",
      "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Emperor-walk_hg.jpg/762px-Emperor-walk_hg.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/penguin.mp3"
    },
    {  
      "letter":"p",
      "label":"Pig",
      "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Sus_scrofa_domesticus%2C_miniature_pig%2C_juvenile.jpg/1280px-Sus_scrofa_domesticus%2C_miniature_pig%2C_juvenile.jpg",
      "sound":"https://www.google.com/logos/fnbx/animal_sounds/pig.mp3"
    }
    ]
  },
  {
    "letter":"q",
    "label":"Quail",
    "image":"https://upload.wikimedia.org/wikipedia/commons/5/59/Blue-headed_quail_dove_%28Starnoenas_cyanocephala%29.JPG",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/q-sound.mp3"
  },
  {
    multi:[
    {
    "letter":"r",
    "label":"Rabbit",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Young_Netherland_Dwarf_rabbit.jpg/1280px-Young_Netherland_Dwarf_rabbit.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/rabbit.mp3"
    },
    {
    "letter":"r",
    "label":"Raccoon",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Three_raccoons_in_a_tree.jpg/1280px-Three_raccoons_in_a_tree.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/raccoon.mp3"
    },
    {
    "letter":"r",
    "label":"Rattlesnake",
    "image":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Crotalus_ruber_02.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/rattlesnake.mp3"
    },
    {
    "letter":"r",
    "label":"Rat",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Sister_ratties_1.jpg/1280px-Sister_ratties_1.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/rat.mp3"
    },
    {
    "letter":"r",
    "label":"Rhinoceros",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Indian_rhinoceros_%28Cincinnati_Zoo%29.jpg/1280px-Indian_rhinoceros_%28Cincinnati_Zoo%29.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/rhinoceros.mp3"
    },
    {
    "letter":"r",
    "label":"Robin",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/European_robin_%28Erithacus_rubecula%29_juvenile.jpg/1280px-European_robin_%28Erithacus_rubecula%29_juvenile.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/robin.mp3"
    },
    {
    "letter":"r",
    "label":"Rooster",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1%2C0_Deutsches_Langschan%2C_braunbr%C3%BCstig.JPG/1280px-1%2C0_Deutsches_Langschan%2C_braunbr%C3%BCstig.JPG",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/rooster.mp3"
    }
    ]
  },
  {
    "letter":"s",
    "label":"Stork",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/White_Stork.jpg/1280px-White_Stork.jpg"
  },
  {
    "letter":"t",
    "label":"Tiger",
    "image":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Siberian_Tiger_by_Malene_Th.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/tiger.mp3",
    color:"orange"
  },
  {
    "letter":"u",
    "label":"Upupa",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Common_Hoopoe_Upupa_epops_by_Dr._Raju_Kasambe_DSCN1570_%282%29.jpg/1280px-Common_Hoopoe_Upupa_epops_by_Dr._Raju_Kasambe_DSCN1570_%282%29.jpg"
  },
  {
    "letter":"v",
    "label":"Vicuna",
    "image":"https://upload.wikimedia.org/wikipedia/commons/3/3e/Vicuna_near_Arequipa.jpg",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/l-sound-llama.mp3"
  },
  {
    "letter":"w",
    "label":"Whale",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Mother_and_baby_sperm_whale.jpg/1280px-Mother_and_baby_sperm_whale.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/humpback-whale.mp3",
    "color":"#2196f3"
  },
  {
    "letter":"x",
    "label":"Xerus",
    "image":"https://upload.wikimedia.org/wikipedia/commons/d/d2/Xerus_inauris.jpg",
    "sound":"http://alphabetimals.com/wp-content/uploads/sounds/r-sound.mp3",
    "color":"tan"
  },
  {
    "letter":"y",
    "label":"Yak",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg/1280px-Bos_grunniens_at_Yundrok_Yumtso_Lake.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/yak.mp3"
  },
  {
    "letter":"z",
    "label":"Zebra",
    "image":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Equus_quagga.jpg/1280px-Equus_quagga.jpg",
    "sound":"https://www.google.com/logos/fnbx/animal_sounds/zebra.mp3"
  },
  ];
  
  var displayAll=false;
  
  for(var i = 0,letter;(letter=letters[i]);i++){
    if(letter.multi){
      if(displayAll){
        for(var j=0,sub;(sub=letter.multi[j]);j++){
          var letterCard = new LetterCard(sub);
          $('main').append(letterCard.node);
        }
      }else{
        var selectedLetter = letter.multi[Math.floor(Math.random()*letter.multi.length)];
        var letterCard = new LetterCard(selectedLetter);
        $('main').append(letterCard.node);
      }
    }else{
      var letterCard = new LetterCard(letter);
      $('main').append(letterCard.node);
    }
  }
  
  
  var trigger = new ScrollTrigger({    
    centerHorizontal: true
    });
});